### ISSUE TITLE
I am confused the scale of the output file

### ISSUE THREAD

**Issue by demainchen** [samsledje/D-SCRIPT#18]
when i try to run the code " dscript embed --seqs /Users/chenwenqi/Desktop/paper/2021-08-12/D-SCRIPT-main/data/seqs/yeast.fasta  --outfile yeast.h5" but the terminal told show that
# 5664 Sequences Loaded
# Approximate Storage Required (varies by average sequence length): ~45.312GB
# Storing to yeast.h5...
"
Is it normal that embedding 5664 sequences need about 45.312GB?

**Comment by samsledje** [comment]
Hi dmeainchen. yes, the embeddings can be quite large due to the 6165 language model dimension, and I am not too surprised at ~50gb for ~5000 sequences. The terminal-shown estimate is extremely rough however, multiplying a constant estimate by the number of sequences in your library -- just to give a rough idea of about how much storage you should expect to be taken up. If many of your sequences are short, you can expect less storage use and vice versa.

If the disk storage size for embeddings is an issue, we are currently working on solutions for that but they may not be available soon i.e. within a month.
